export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const SUBMIT_CUSTOMER_SURVEY = 'SUBMIT_CUSTOMER_SURVEY';
export const SUBMIT_CUSTOMER_SURVEY_FAILED = 'SUBMIT_CUSTOMER_SURVEYS_FAILED';

// export const FETCH_TAB = 'FETCH_TAB'; // Get a table's tab which holds their meals and costs
export const GET_CUSTOMER_TAB = 'GET_CUSTOMER_TAB';
export const GET_CUSTOMER_TAB_FAILED = 'GET_CUSTOMER_TAB_FAILED';
